spring:
  application:
    name: club-catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    url: jdbc:postgresql://localhost:5433/clubs
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 4
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 3000
        multiplier: 1.2
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ClubCatalog
        registration:
          keycloak:
            provider: keycloak
            client-name: club-catalog-service
            client-id: club-catalog-service
            client-secret: club-keycloak-secret
            scope: openid
management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 20
      min-spare: 5
  shutdown: graceful
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect

club:
  greeting: Welcome to the Club from local properties file!
