CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SEQUENCE IF NOT EXISTS bookings_booking_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS clubs_club_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS coaches_coach_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS courts_court_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS lessons_lesson_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS members_member_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS roles_role_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tournaments_tournament_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_roles_user_role_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_user_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE bookings
(
    booking_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    court_id     INTEGER                                  NOT NULL,
    member_id    INTEGER                                  NOT NULL,
    booking_date date                                     NOT NULL,
    start_time   time WITHOUT TIME ZONE                   NOT NULL,
    end_time     time WITHOUT TIME ZONE                   NOT NULL,
    CONSTRAINT bookings_pkey PRIMARY KEY (booking_id)
);

CREATE TABLE clubs
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(100)                             NOT NULL,
    street_address VARCHAR(255),
    city           VARCHAR(100),
    state          VARCHAR(100),
    postal_code    VARCHAR(20),
    country        VARCHAR(100),
    phone_number   VARCHAR(20),
    email          VARCHAR(100),
    description    TEXT,
    location       GEOMETRY,
    CONSTRAINT clubs_pkey PRIMARY KEY (id)
);

CREATE TABLE coaches
(
    coach_id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    club_id        INTEGER                                  NOT NULL,
    first_name     VARCHAR(50)                              NOT NULL,
    last_name      VARCHAR(50)                              NOT NULL,
    date_of_birth  date                                     NOT NULL,
    email          VARCHAR(100)                             NOT NULL,
    phone_number   VARCHAR(20),
    street_address VARCHAR(255),
    city           VARCHAR(100),
    state          VARCHAR(100),
    postal_code    VARCHAR(20),
    country        VARCHAR(100),
    hire_date      date                                     NOT NULL,
    specialization VARCHAR(50),
    CONSTRAINT coaches_pkey PRIMARY KEY (coach_id)
);

CREATE TABLE courts
(
    court_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    club_id      INTEGER                                  NOT NULL,
    court_number INTEGER                                  NOT NULL,
    surface_type VARCHAR(50),
    CONSTRAINT courts_pkey PRIMARY KEY (court_id)
);

CREATE TABLE lessons
(
    lesson_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    club_id     INTEGER                                  NOT NULL,
    coach_id    INTEGER                                  NOT NULL,
    lesson_date date                                     NOT NULL,
    start_time  time WITHOUT TIME ZONE                   NOT NULL,
    end_time    time WITHOUT TIME ZONE                   NOT NULL,
    level       VARCHAR(50),
    CONSTRAINT lessons_pkey PRIMARY KEY (lesson_id)
);

CREATE TABLE members
(
    member_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    club_id               INTEGER                                  NOT NULL,
    first_name            VARCHAR(50)                              NOT NULL,
    last_name             VARCHAR(50)                              NOT NULL,
    date_of_birth         date                                     NOT NULL,
    email                 VARCHAR(100)                             NOT NULL,
    phone_number          VARCHAR(20),
    street_address        VARCHAR(255),
    city                  VARCHAR(100),
    state                 VARCHAR(100),
    postal_code           VARCHAR(20),
    country               VARCHAR(100),
    membership_start_date date                                     NOT NULL,
    membership_end_date   date,
    membership_type       VARCHAR(50),
    CONSTRAINT members_pkey PRIMARY KEY (member_id)
);

CREATE TABLE roles
(
    role_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(50)                              NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE tournaments
(
    tournament_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    club_id         INTEGER                                  NOT NULL,
    tournament_name VARCHAR(100)                             NOT NULL,
    start_date      date                                     NOT NULL,
    end_date        date                                     NOT NULL,
    CONSTRAINT tournaments_pkey PRIMARY KEY (tournament_id)
);

CREATE TABLE user_roles
(
    user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      INTEGER                                  NOT NULL,
    role_id      INTEGER                                  NOT NULL,
    club_id      INTEGER,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_role_id)
);

CREATE TABLE users
(
    user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(50)                              NOT NULL,
    password_hash VARCHAR(255)                             NOT NULL,
    first_name    VARCHAR(50)                              NOT NULL,
    last_name     VARCHAR(50)                              NOT NULL,
    email         VARCHAR(100)                             NOT NULL,
    phone_number  VARCHAR(20),
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE coaches
    ADD CONSTRAINT coaches_email_key UNIQUE (email);

ALTER TABLE members
    ADD CONSTRAINT members_email_key UNIQUE (email);

ALTER TABLE roles
    ADD CONSTRAINT roles_role_name_key UNIQUE (role_name);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT users_username_key UNIQUE (username);

ALTER TABLE bookings
    ADD CONSTRAINT bookings_court_id_fkey FOREIGN KEY (court_id) REFERENCES courts (court_id) ON DELETE NO ACTION;

ALTER TABLE bookings
    ADD CONSTRAINT bookings_member_id_fkey FOREIGN KEY (member_id) REFERENCES members (member_id) ON DELETE NO ACTION;

ALTER TABLE coaches
    ADD CONSTRAINT coaches_club_id_fkey FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE NO ACTION;

ALTER TABLE courts
    ADD CONSTRAINT courts_club_id_fkey FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE NO ACTION;

ALTER TABLE lessons
    ADD CONSTRAINT lessons_club_id_fkey FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE NO ACTION;

ALTER TABLE lessons
    ADD CONSTRAINT lessons_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES coaches (coach_id) ON DELETE NO ACTION;

ALTER TABLE members
    ADD CONSTRAINT members_club_id_fkey FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE NO ACTION;

ALTER TABLE tournaments
    ADD CONSTRAINT tournaments_club_id_fkey FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT user_roles_club_id_fkey FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE NO ACTION;
